name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: "Kernel version to build"
        required: true
        default: "5.10.228"
      kernel_branch:
        description: "Kernel branch to build"
        required: true
        default: "v5.x"

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container: debian:bookworm-slim
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends bash ca-certificates git tar xz-utils wget build-essential flex bison libssl-dev libelf-dev bc kmod

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Download Kernel
        run: wget https://cdn.kernel.org/pub/linux/kernel/${{ inputs.kernel_branch }}/linux-${{ inputs.kernel_version }}.tar.xz

      - name: Extract Kernel
        run: tar -xf linux-${{ inputs.kernel_version }}.tar.xz

      - name: Copy Kernel Config
        run: cp ./kernel/${{ inputs.kernel_version }}.config ./linux-${{ inputs.kernel_version }}/.config

      - name: Build Kernel
        env:
          KERNEL_VERSION: ${{ inputs.kernel_version }}
        run: ./kernel/build.sh

      - name: Prepare Artifacts
        run: |
          mv /tmp/build-modules/lib/modules/${{ inputs.kernel_version }}-steam ../boot/
          mv arch/arm/boot/zImage ../boot/
          mv arch/arm/boot/dts/berlin2cd-valve-steamlink.dtb

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ inputs.kernel_version }}-steam
          path: boot/
