name: Build Debian Image
on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: "Kernel version to build"
        required: true
        default: "5.10.228"
      kernel_branch:
        description: "Kernel branch to build"
        required: true
        default: "v5.x"
      debian_version:
        description: "Debian version to use"
        required: true
        default: "bullseye"

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container: debian:bookworm-slim
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends bash ca-certificates git tar xz-utils wget build-essential flex bison libssl-dev libelf-dev bc kmod

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Download Kernel
        run: wget https://cdn.kernel.org/pub/linux/kernel/${{ inputs.kernel_branch }}/linux-${{ inputs.kernel_version }}.tar.xz

      - name: Extract Kernel
        run: tar -xf linux-${{ inputs.kernel_version }}.tar.xz

      - name: Copy Kernel Config
        run: cp ./kernel/${{ inputs.kernel_version }}.config ./linux-${{ inputs.kernel_version }}/.config

      - name: Build Kernel
        env:
          KERNEL_VERSION: ${{ inputs.kernel_version }}
        run: ./kernel/build.sh

      - name: Prepare Artifacts
        working-directory: linux-${{ inputs.kernel_version }}
        run: |
          mv /tmp/build-modules/lib/modules/${{ inputs.kernel_version }}-steam ../boot/
          mv arch/arm/boot/zImage ../boot/
          mv arch/arm/boot/dts/berlin2cd-valve-steamlink.dtb ../boot/
          rm -rf ../boot/${{ inputs.kernel_version }}-steam/build
          rm -rf ../boot/${{ inputs.kernel_version }}-steam/source

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ inputs.kernel_version }}-steam
          path: boot/

  build-rootfs:
    runs-on: ubuntu-latest
    needs: build-kernel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "false"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@master
        with:
          name: kernel-${{ inputs.kernel_version }}-steam
          path: kernel

      - name: Build RootFS Docker Image
        run: docker buildx build --platform linux/arm/v7 --build-arg KERNEL_VERSION=${{ inputs.kernel_version }} --build-arg DEBIAN_VERSION=${{ inputs.debian_version }} --rm -f rootfs/Dockerfile --tag steamlink-debian:latest

      - name: Create RootFS tarball
        run: |
          docker create --platform linux/arm/v7 -t -i --name steamlink-debian-rootfs steamlink-debian:latest
          docker export steamlink-debian-rootfs -o rootfs.tar

      - name: Create disk image
        run: |
          dd if=/dev/zero of=steamlink-debian-${{ inputs.debian_version }}-${{ inputs.kernel_version }}.img bs=1M count=2048
          mkfs.ext3 steamlink-debian-${{ inputs.debian_version }}-${{ inputs.kernel_version }}.img

      - name: Extract RootFS
        run: |
          sudo mkdir /mnt/disk
          sudo mount steamlink-debian-${{ inputs.debian_version }}-${{ inputs.kernel_version }}.img /mnt/disk
          sudo tar -xpf rootfs.tar -C /mnt/disk/
          sudo umount -l steamlink-debian-${{ inputs.debian_version }}-${{ inputs.kernel_version }}.img

      - name: Upload disk image
        uses: actions/upload-artifact@v4
        with:
          name: steamlink-debian-${{ inputs.debian_version }}-${{ inputs.kernel_version }}
          path: steamlink-debian-${{ inputs.debian_version }}-${{ inputs.kernel_version }}.img
